### ISSUE TITLE
Please add support for record of type CAA

### ISSUE THREAD

**Issue by nbensa** [veksh/terraform-provider-godaddy-dns#15]
https://letsencrypt.org/docs/caa/

I could do without this record type, but I prefer not to drop it from the domains I have.

Thanks!

**Comment by veksh** [comment]
Unfortunately, GoDaddy API does not allow to manage CAA records: [documentation](https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName) states that DNS Record Type could be "A, AAAA, CNAME, MX, NS, SOA, SRV, TXT". No need to drop it from domain config if you feel like having it, but it cannot be altered with Terraform for now.

**Comment by nbensa** [comment]
That's weird. I had CAA records with CruGlobal/godaddy and the following TF block:

```
resource "godaddy_domain_record" "eneabe_com" {
  domain = "eneabe.com"
  record {
    name = "@"
    type = "CAA"
    data = "128 issue \"letsencrypt.org\""
    ttl  = 600
  }
}
```

**Comment by veksh** [comment]
Weird indeed :)
For me, API rejects all calls with `CAA` record type
```
alex@alexair:godaddy$ curl "https://api.godaddy.com/v1/domains/veksh.in/records/CAA" -H "Authorization: sso-key $GODADDY_API_KEY:$GODADDY_API_SECRET"
{"code":"INVALID_VALUE_ENUM","message":"type not any of: A, AAAA, CNAME, MX, NS, SOA, SRV, TXT"}
```

although I could see manually created CAA records in "all records" list
```
curl "https://api.godaddy.com/v1/domains/veksh.in/records" -H "Authorization: sso-key $GODADDY_API_KEY:$GODADDY_API_SECRET" | jq '.[] | select(.type == "CAA")'
{
  "data": "otherca.com",
  "name": "caatest.man-test",
  "ttl": 3600,
  "type": "CAA"
}
{
  "data": "letsencrypt.org",
  "name": "caatest.man-test",
  "ttl": 3600,
  "type": "CAA"
}
```

So I guess that CAA records could not be managed with the official GoDaddy API after all.

Are you sure that you really have this record in your domain? If your example uses real domain name, then I have a bad news for you: its CAA record is really absend
```
alex@alexair:~$ host -t CAA eneabe.com
eneabe.com has no CAA record
alex@alexair:~$ host -t CAA caatest.man-test.veksh.in
caatest.man-test.veksh.in has CAA record 0 issue "otherca.com"
caatest.man-test.veksh.in has CAA record 128 issue "letsencrypt.org"
```

You could confirm that with any DNS lookup tool, like [this one](https://www.entrust.com/ru/resources/certificate-solutions/tools/caa-lookup) specially designed for CAA records, or [GoDaddy management console](https://dcc.godaddy.com/control/portfolio/eneabe.com/settings).

**Comment by nbensa** [comment]
Yes. I'm sure I had the CAA record. 

I removed the record yesterday after I upgraded to your GoDaddy plugin :-)

But you got me thinking. So I added the CruGlobal/godday provider once again and recreated the CAA record using Terraform.

Terraform accepts the change. Doesn't touch any other record. I mean, after apply, the zone looks correct for every record except one little detail. The CAA record was not created!! I confirmed this using the GoDaddy console.

It was long time ago, so I think what actually happen is I added those records from the GoDaddy console, then I added the records in my terraform manifests and got the history all screwed up in my head. 

The CAA record you could see now, is the one I created using the GoDaddy admin console.

I'm sorry for wasting your time.

**Comment by veksh** [comment]
No problem, and I'm glad that the mystery is resolved after all :)
