### ISSUE TITLE
Does this provider support SOA records?

### ISSUE THREAD

**Issue by elektron9** [veksh/terraform-provider-godaddy-dns#16]
Thanks for the wonderful Terraform provider, @veksh! I was curious to know if the provider supports SOA records, and if not, what it might take to add support for them.

Thank you!

**Comment by veksh** [comment]
Thank you for your kind words!
Currently SOA records are not supported. SOA records are a bit special for domains hosted on GoDaddy and most probably could not be managed with API -- maybe it is possible with [premium subscription](https://uk.godaddy.com/help/premium-dns-features-332), cannot check as I do not have one. AFAIR SOA records are pretty useless except for (BIND) secondary DNS servers and zone transfers. 

What is your use case for them? Maybe you just want to delegate subdomain somewhere else? Then NS records will serve you better :)

**Comment by elektron9** [comment]
Thanks for getting back to me. I think you're correct - I had exported my DNS Zone file via the GoDaddy UI and saw that there was an SOA record present in the exported listing, so sought to create a 1:1 replica of the records in Terraform.

However, after further investigation I believe the values within that SOA record are all default values created by GoDaddy, so it may be safe to leave that record unmanaged by Terraform if we are just using the defaults.

Thanks, I will close this out for now!
