### ISSUE TITLE
Add Support for SRV

### ISSUE THREAD

**Issue by DevopsMercenary** [veksh/terraform-provider-godaddy-dns#39]
Creating an issue to see if your fine work can support SRV ?

**Comment by veksh** [comment]
Hi! It is definitely possible, but after the recent GoDaddy policy change I've suspended the developmnent for this project (as mentioned in readme). For now I cannot even test my code against the real API, and so decided to better keep it in a last known good state. Maybe they'll reopen API access to the general public one day, stay tuned :)

**Comment by DevopsMercenary** [comment]
Well, that's a kick in the teeth.  Maybe my team will just move away from GoDaddy.

Sorry to hear about the inconvenience.
