### ISSUE TITLE
Importing DMARC records fail

### ISSUE THREAD

**Issue by StummeJ** [veksh/terraform-provider-godaddy-dns#8]
Since a DMARC record can contain `:` for parameters like `rua` and `ruf`, the choice of using `:` as a delimiter causes import errors

Example:
```
import {
  to = godaddy-dns_record.dmarc
  id = "domain.com:TXT:_dmarc:'v=DMARC1;p=quarantine;pct=100;rua=mailto:dmarc@domain.com;ruf=mailto:dmarc@domain.com;fo=1'"
}
```

**Comment by veksh** [comment]
Thanks for noting that. I've updated the code to allow ":" in TXT fields on import, it should be OK now.
